include('../../../../bnpl-edge-service/Tiltfile')
include('../../../../bnpl-order-service/Tiltfile')
include('../../../../bnpl-catalog-service/Tiltfile')
include('../../../../bnpl-dispatcher-service/Tiltfile')

update_settings(max_parallel_updates=1)
